# Generated by Django 5.2.6 on 2025-09-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cta_text', models.CharField(default='Shop Now', max_length=100)),
                ('cta_link', models.URLField(blank=True, max_length=300, null=True)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, help_text='Main image for the slide', null=True, upload_to='hero/slides/images/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile-optimized image', null=True, upload_to='hero/slides/mobile/')),
                ('video', models.FileField(blank=True, help_text='Optional background video', null=True, upload_to='hero/slides/videos/')),
                ('bg_color', models.CharField(default='from-blue-600 to-purple-600', help_text='Tailwind gradient e.g. from-blue-600 to-purple-600', max_length=100)),
                ('overlay_color', models.CharField(default='black', help_text='Overlay color (CSS color)', max_length=50)),
                ('overlay_opacity', models.FloatField(default=0.4, help_text='Overlay opacity (0 = none, 1 = full)')),
                ('text_color', models.CharField(default='white', help_text='Text color (CSS)', max_length=50)),
                ('align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Text alignment', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=5000, help_text='Slide duration in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
